# Generated by Django 5.0.6 on 2024-05-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')
                ),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nacionality', models.CharField(
                    blank=True,
                    max_length=100,
                    null=True, choices=[
                        ('USA', 'Estados Unidos'),
                        ('BR', 'Brasil')],))
            ],
        ),
    ]
